context("conversions")

## Mostly regression tests for the conversions.  This will grow as I
## identify bugs and should act to stop them reappearing.
test_that("difficult conversions", {
  redis_flatten_command <- function(list) {
    .Call("redis_flatten_command", list, PACKAGE="redux")
  }
  redis_check_command <- function(list) {
    .Call("redis_check_command", list, PACKAGE="redux")
  }

  ## Was throwing an error because of the 0L in there.
  x <- list("SCAN", 0L, list("MATCH", "Mk0FylY:*"), NULL)
  expect_equal(redis_flatten_command(x), unlist(x, FALSE))

  ## As generated by
  x <- list("foo", 1:2)
  expect_equal(redis_flatten_command(x), list("foo", 1:2))
  expect_equal(redis_check_command(x), list("foo", c("1", "2")))
})
