##' Create a Redis connection.  This function is designed to be used
##' in other packages, and not directly by end-users.  However, it is
##' possible and safe to use.  See the \code{RedisAPI} package for a
##' complete example.
##'
##' This function creates a list of functions, appropriately bound to
##' a pointer to a Redis connection.  This is designed for package
##' authors to use so without having to ever deal with the actual
##' pointer itself (which cannot be directly manipulated from R
##' anyway).
##'
##' The returned list has elements, all of which are functions:
##'
##' \describe{
##' \item{\code{config()}}{The configuration information}
##'
##' \item{\code{reconnect()}}{Attempt reconnection of a connection
##' that has been closed, through serialisation/deserialiation or
##' through loss of internet connection.}
##'
##' \item{command(cmd)}{Run a Redis command.  The format of this
##' command will be documented elsewhere.}
##'
##' \item{pipeline(cmds)}{Run a pipeline of Redis commands.}
##'
##' \item{subscribe(channel, callback, envir)}{this will change...}
##'
##' }
##'
##' @title Create a Redis connection
##' @param config Configuration parameters as generated by
##'   \code{\link[RedisAPI]{redis_config}}.
##' @useDynLib redux, .registration = TRUE
##' @export
##'
redis_connection <- function(config) {
  ptr <- redis_connect(config)
  list(
    config=function() {
      config
    },
    reconnect=function() {
      ptr <<- redis_connect(config)
      invisible()
    },
    command=function(cmd) {
      redis_command(ptr, cmd)
    },
    pipeline=function(cmds) {
      redis_pipeline(ptr, cmds)
    },
    subscribe=function(channel, callback, envir=parent.frame(), pattern=FALSE) {
      redis_subscribe(ptr, channel, callback, envir, pattern)
    })
}

##' @export
print.redis_status <- function(x, ...) {
  cat(sprintf('[Redis: %s]\n', x))
}
